version: '3'

services:

  dbserver-wordpress:
    restart: always
    hostname: dbserver-wordpress
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpressuser"
      MYSQL_PASSWORD: "4linux"
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    networks:
    - 4labs
    volumes:
    - "./data:/var/lib/mysql"
  
  webserver-wordpress:
    restart: always
    image: wordpress:latest
    ports:
    - 80:80
    environment:
      WORDPRESS_DB_HOST: "dbserver-wordpress"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: "wordpressuser"
      WORDPRESS_DB_PASSWORD: "4linux"
    networks:
    - 4labs
    volumes:
    - "./wpsite:/var/www/html"

networks:
  4labs:
    external: true
